### ISSUE TITLE
List Intend doesn't work As espected

### ISSUE THREAD

**Issue by empik-foto-it** [cristianvasquez/obsidian-prettify#31]
It doesn't work As espected:
 (Obsidian 0.10.2  plugin 0.0.6)
(Obsidian 0.10.4 plugin 0.0.8)
 
 1. one space:
 
![image](https://user-images.githubusercontent.com/37656900/102979356-3ff3e180-4506-11eb-9093-dd034e21024c.png)

  afer `-` one space -> ok, but intend has two spaces (two dots)
  
  Expected results:
  - [space] TEXT
  [space] -  [space] TEXT
  [space][space] -  [space] TEXT

2.  mixed
![image](https://user-images.githubusercontent.com/37656900/102979491-6ca7f900-4506-11eb-9a4a-c93db5f21413.png)

  - first inted has 3- space after a `-` char , secound  has 4 spaces which make an intend and 1 space after a  `-` 

Expected results:
- I do not know... mayby like a tab right now?
  
3. tab
![image](https://user-images.githubusercontent.com/37656900/102979689-b55fb200-4506-11eb-8205-cef13e2a8dcd.png)

  - first inted has 3- space after a `-` char , secound  has 4 spaces which make an intend and 3 spaces after a  `-` . there is no a TAB char at all
  
Expected results:
  - [1 space] TEXT
  [tab] -  [ 1space] TEXT
  [tab][tab] -  [ 1space] TEXT

_Originally posted by @dariuszkowalski-com in https://github.com/cristianvasquez/obsidian-prettify/issues/24#issuecomment-750026911_

**Comment by cristianvasquez** [comment]
What would be the use case?

**Comment by dariuszkowalski-com** [comment]
1. I don't know how each option should work. 
![image](https://user-images.githubusercontent.com/37656900/103413994-390b4580-4b7c-11eb-9c55-86eecec9177a.png)

espetialy `tab` -> where is no Tab at all -> thera are `spaces`

2. Tabs are useful because I can use CSS Snippet which  will help me to show level of intend in lists
![image](https://user-images.githubusercontent.com/37656900/103413943-019c9900-4b7c-11eb-8fd8-bc0a704def21.png)

3. For me this option could be synchronized or repleaced by reading the Obsidian parameters:
![image](https://user-images.githubusercontent.com/37656900/103414051-8ab3d000-4b7c-11eb-9b9a-cce2d0d9be78.png)

When I set `Use tabs` it means that I prefer to have `tabs` then `spaces'

**Comment by cristianvasquez** [comment]
Definitely open to a Pull Request since I'm not sure when I'd be able to get to this.

**Comment by jjspace** [comment]
Instead of creating a new issue I'll tag onto this one. To me the `List Indent` setting should *only* affect what's before the bullet character. It seems to be appropriately following what I have set in Obsidian regarding point 3 of @dariuszkowalski-com's comment above regarding inserting spaces instead of tabs when I have List Indent to tabs. However, the problem I'm running into is that it puts extra spaces *after* the bullet character. Regardless which option I have set for List Indent every line should always be `[indent characters] [bullet] [ONE space] TEXT`

**Comment by ivan-lednev** [comment]
I might get to fixing this, but for now I don't see any way of doing this except copying & modifying the list-item handler from [here](https://github.com/syntax-tree/mdast-util-to-markdown/blob/main/lib/handle/list-item.js), the way @cristianvasquez did it before this [commit](https://github.com/cristianvasquez/obsidian-prettify/commit/cc230a34c72163233457d5b34dff61e7e71844e6)

Not sure if it's worth doing it this way. Any comments & ideas are welcome.

**Comment by rodrigo-rufino** [comment]
Any plans to fix this one? 👀

**Comment by tuan3w** [comment]
Hi all,
I find this workaround solution. Just update `runPrettifier` function in `main.ts`

```typescript
 runPrettifier() {
    const view = this.app.workspace.activeLeaf.view;
    if (view instanceof MarkdownView) {
      // Do work here
      const editor = view.sourceMode.cmEditor;

      // Remember the cursor
      const cursor = editor.getCursor();

      editor.execCommand("selectAll");
      let text = editor.getSelection();

      prettifier(text, this.settings, { today: moment(), tags: [] })
        .then((data) => {
          let output = String(data || '');
          // modify the output generated by remark
          // support image link. ![[imagefile]]
          //@ts-ignore
          output = output.replaceAll('!\\[\\[', '![[');
         // fix indentation issue
          output = output.replace(/- {2,}/g, '- ');
          //@ts-ignore
          output = output.replaceAll('    ', '\t');
          
          try {
            // Calculate difference of lines and provide feedback
            const n_before = String(data).split(/\r\n|\r|\n/).length;
            const n_after = String(text).split(/\r\n|\r|\n/).length;
            const lines_changed = n_before - n_after;
            if (lines_changed != 0) {
              if (lines_changed > 0) {
                new Notice("Prettifier: added " + lines_changed + " lines.");
              } else {
                new Notice("Prettifier: removed " + lines_changed + " lines.");
              }
            }
            // Update the cursor
            if (cursor.line) {
              cursor.line = cursor.line + lines_changed;
            }
          } catch (err) {
            console.error(err);            
          }

          editor.replaceSelection(output, "start");
          editor.setCursor(cursor);
        }).catch((err) => {
          console.error(err);
          if (err.message) {
            new Notice(err.message);
          }
        });
    }
  }
```

**Comment by rodrigo-rufino** [comment]
@tuan3w Ohhh nice! What do you think of opening a Pull Request with this code?

**Comment by rodrigo-rufino** [comment]
@cristianvasquez I noticed that the code @tuan3w code was removed in the 0.1.0 release, breaking the indentation again. Do you have any plans to implement this fix again?

**Comment by EEE8D** [comment]
Please fix this again

**Comment by cristianvasquez** [comment]
I updated the plugin to accept one space or a tab :)
